"""empty message

Revision ID: 2f419a0a8c86
Revises: f87c1dd87259
Create Date: 2020-11-11 00:50:50.153398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f419a0a8c86'
down_revision = 'f87c1dd87259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('class_number', sa.Integer(), nullable=True))
    op.drop_column('session', 'class_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('class_num', sa.INTEGER(), nullable=True))
    op.drop_column('session', 'class_number')
    # ### end Alembic commands ###
