"""new table names

Revision ID: 93ef6af7fac6
Revises: 
Create Date: 2020-11-15 14:58:34.620063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ef6af7fac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursetable',
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('class_num', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('class_name')
    )
    op.create_table('usertable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=128), nullable=True),
    sa.Column('venmo', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=500), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=128), nullable=True),
    sa.Column('price_range', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usertable_email'), 'usertable', ['email'], unique=True)
    op.create_index(op.f('ix_usertable_username'), 'usertable', ['username'], unique=True)
    op.create_table('carttable',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usertable.id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('sessiontable',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('zoom_link', sa.String(length=120), nullable=True),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.Column('time', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('booked', sa.String(length=120), nullable=True),
    sa.Column('tutor', sa.Integer(), nullable=True),
    sa.Column('tutee', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('class_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutee'], ['usertable.id'], ),
    sa.ForeignKeyConstraint(['tutor'], ['usertable.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('ratingtable',
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('tutor', sa.Integer(), nullable=True),
    sa.Column('tutee', sa.Integer(), nullable=True),
    sa.Column('session', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('class_num', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('rating_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session'], ['sessiontable.session_id'], ),
    sa.ForeignKeyConstraint(['tutee'], ['usertable.id'], ),
    sa.ForeignKeyConstraint(['tutor'], ['usertable.id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratingtable')
    op.drop_table('sessiontable')
    op.drop_table('carttable')
    op.drop_index(op.f('ix_usertable_username'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_email'), table_name='usertable')
    op.drop_table('usertable')
    op.drop_table('coursetable')
    # ### end Alembic commands ###
