"""empty message

Revision ID: b9fa419fc005
Revises: dd51535c9f59
Create Date: 2020-11-03 21:48:19.799143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fa419fc005'
down_revision = 'dd51535c9f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('zoom_link', sa.String(length=120), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('tutor', sa.Integer(), nullable=True),
    sa.Column('tutee', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('class_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('zoom_link')
    )
    op.create_index(op.f('ix_session_date'), 'session', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_date'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###
