"""empty message

Revision ID: cdea4c1c0099
Revises: e9386e84224f
Create Date: 2020-11-05 10:09:17.037006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdea4c1c0099'
down_revision = 'e9386e84224f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('school', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('venmo', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'venmo')
    op.drop_column('user', 'school')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'name')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
