"""redoing tables_v2

Revision ID: f87c1dd87259
Revises: 
Create Date: 2020-11-10 19:41:40.598629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87c1dd87259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('class_num', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('class_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=128), nullable=True),
    sa.Column('venmo', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=500), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=128), nullable=True),
    sa.Column('price_range', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessions', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('tutor', sa.Integer(), nullable=True),
    sa.Column('tutee', sa.Integer(), nullable=True),
    sa.Column('session', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('class_num', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('rating_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutee'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tutor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_table('session',
    sa.Column('zoom_link', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.Column('time', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('booked', sa.String(length=120), nullable=True),
    sa.Column('tutor', sa.Integer(), nullable=True),
    sa.Column('tutee', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('class_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutee'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tutor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('zoom_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.drop_table('rating')
    op.drop_table('cart')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('course')
    # ### end Alembic commands ###
